.TH "ipsilon" "7" "2013" "Ipsilon" "Ipsilon Identity Provider"
.SH "NAME"
ipsilon
.SH "DESCRIPTION"
Ipsilon is an Identity Provider (IdP) that implements standard Authentication
and FEderation protocols like SAML, and integrates with Enterprise
Authentication systems to provide easy to use Single Sign On capabilities to
Web Applications and Services.
