RUN yum update -y \
    && yum install -y which
# This should be kept in sync with the develop page on the website.
# Distro-specific packages should go in the distro sub-dockerfiles.
RUN yum install -y make pylint python-pep8 python-openid python-openid-teams \
        python-openid-cla python-cherrypy m2crypto lasso-python \
        python-sqlalchemy python-ldap python-pam python-fedora \
        freeipa-python httpd mod_auth_mellon postgresql-server \
        openssl mod_wsgi python-jinja2 python-psycopg2 sssd \
        libsss_simpleifp openldap-servers mod_auth_gssapi krb5-server \
        socket_wrapper nss_wrapper python-requests-kerberos python-lesscpy\
        nodejs-less krb5-workstation python-sssdconfig sqlite python-jwcrypto \
        mod_ssl mod_auth_openidc python-jwcrypto
