#!/usr/bin/python
#
# Copyright (C) 2015 Ipsilon project Contributors, for license see COPYING

import sys
from ipsilon import find_config
from ipsilon.tools import dbupgrade
import logging

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    def_logger = logging.getLogger()
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.ERROR)
    def_logger.addHandler(ch)

    try:
        dbupgrade.execute_upgrade(find_config())
    except Exception as ex:
        logger.error(ex)
        sys.exit(1)
