#!/usr/bin/python
#
# Copyright (C) 2015 Ipsilon project Contributors, for license see COPYING

__requires__ = ['sqlalchemy >= 0.8']
import pkg_resources  # pylint: disable=unused-import

import sys
import logging
logging.basicConfig(level=logging.INFO)

from ipsilon import find_config
from ipsilon.tools import dbupgrade

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    try:
        dbupgrade.execute_upgrade(find_config())
    except Exception as ex:
        logger.error('Error upgrading database', exc_info=True)
        sys.exit(1)
